config/routes.rb
LifepackTaskRecord::Application.routes.draw do
  get "mo_session/index"

  get "mo_session/create"

  resources :tasks ,:only =>[:index,:show,:new,:edit,:create,:update] do
    delete :delete_task, :on=>:member
    get :past_task_lists, :on=>:collection
  end
  resources :sessions ,:only =>[:index,:new,:create,:destroy] do
      get :unauthenticated,:on=>:member
  end
  resources :users, :only => [:show,:new,:edit,:create,:update,:destroy] 
  resources :groups, :only => [:index,:show,:new,:edit,:create,:update,:destroy]
  

  root :to => "tasks#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/group.rb
class Group < ActiveRecord::Base
  scope :latest ,order('created_at desc')
  belongs_to :user
  
  def self.your_group(id)
    @groups =Group.where('user_id=?',id)
    if @groups==nil
      return Array.new
    else
      return @groups
    end
  end

  def self.select_item_groups(id)
     @groups =Group.where('user_id=?',id)
     @default_group = Group.new
     @default_group.name="NOT SELECT"
     @default_group.id=0
     @default_group.description="NOT SELECT"
     @groups.push  @default_group
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :html,:xml
  def index
    if session[:login_user] == nil
      redirect_to :controller=>'sessions'
    end
    @login_user =set_user
    @groups = Group.where(["owner_id=?",@login_user]).latest
    @join_groups = Group.where(["user_id=?",@login_user]).latest
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.xml  { render :xml => @groups }
    #end
  end

  def new
    @login_user =set_user
    @group = Group.new
     respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  def create
    @login_user =set_user
    @group = Group.new(params[:group])
    @group.user_id = @login_user.id
    @group.owner_id = @login_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @login_user =set_user
  end

  def update
    @login_user =set_user
  end

  def destroy
    @login_user =set_user
  end

  def show
   @login_user =set_user
   @group=Group.find(params[:id])
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="group_form">
  <div class="field">
    <%= f.label :title, 'グループ名' %>：
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description ,'詳細'%>：<br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    所属メンバー：<br />
   --</div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/groups/_menu.html.erb
<table>
  <tr><td class="menu_text">
  <%= link_to 'グループ設定', :controller =>'group', :action => 'index' %> |
  <%= link_to 'タスク一欄へ',  :controller =>'tasks', :action => 'index' %>
  </td></tr>
</table>

app/views/groups/index.html.erb
<%= link_to '新規グループ', new_group_path %>
<hr>
<p id="notice"><%= notice %></p>
<div class="sub_header_info">グループ一覧</div>
<table>
  <tr>
    <th>グループ名</th>
    <th>グループ説明</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to '編集する', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/groups/new.html.erb
<h2>グループ作成</h2>

<%= render 'form' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>グループ名:</b>
  <%= @group.name %>
</p>
<p>
  <b>詳細:</b>
  <%= @group.description %>
</p>